### PR TITLE
split the existing profiles into light/verbose and add a verbose mode for bthport

### PR DESCRIPTION
**Pull request by arvindaiyar**
This splits the existing Bluetooth profile into 2 modes - a Light mode and a Verbose mode. The Light mode is whatever was there before and will be used in Repro mode etc. The new Verbose mode will allow for changing the verbosity of existing providers - I just added bthport for now. 

I tested both profiles and verified that bthport logs are collected at the correct verbosity in each

### CODE REVIEW

**Comment by drache42** [comment]
Keep light and verbose provides next to each other. Then it's easier to see if a provider already has 2 versions

**Comment by erik-pe** [comment]
>       <Collectors>

Taking requests for other verbose level providers? I could see the following being useful:

Microsoft.Windows.Bluetooth.ForkbeardCore
Microsoft.Windows.Bluetooth.ForkbeardPolicy
Microsoft.Windows.Bluetooth.Profiles.Dis
Microsoft.Windows.Bluetooth.Profiles.Gap
Microsoft.Windows.Bluetooth.Profiles.Gatt
Microsoft.Windows.Bluetooth.Protocols.Att
Microsoft.Windows.Bluetooth.WPP.bthusb

---
Refers to: bluetooth/tracing/BluetoothStack.wprp:1405 in 874af02. [](commit_id = 874af02ffba0e53af6f9c7fe0d03d62b40697f39, deletion_comment = False)

**Comment by erik-pe** [comment]
>       <Collectors>

In terms of stuff that we're going to test at UPF, at least.

---
In reply to: [391869591](https://github.com/Microsoft/busiotools/pull/11#issuecomment-391869591) [](ancestors = 391869591)

---
Refers to: bluetooth/tracing/BluetoothStack.wprp:1405 in 874af02. [](commit_id = 874af02ffba0e53af6f9c7fe0d03d62b40697f39, deletion_comment = False)

**Comment by arvindaiyar** [comment]
i think ill just leave it as is and leave additions to you guys ... i just wanted to get the "template" up so that additions can follow the pattern.

**Comment by arvindaiyar** [comment]
One more thing : the default profile if you dont specify one seems to be Verbose. I've updated the readme to reflect that.

**Pull request merged**
