### PR TITLE
Add one new test for accelerometer

### PR DESCRIPTION
**Pull request by jianliu617**
Add sensor resolution and noise density new test for accelerometer.

### CODE REVIEW

**Comment by jianliu617** [comment]
@jialzhu, Could you please review this PR? We have tested on real device. Thank you.

**Comment by jianliu617** [comment]
@sastorer-ms, could you please review this PR? Thank you.

**Comment by jianliu617** [comment]
@sastorer-ms, Thank you for approving this pull request. Could you please also merge it?

BTW: If possible, would you mind sharing the release cadence of SensorExplorer to Microsoft Store? Thank you.

**Comment by sastorer-ms** [comment]
@jianliu617 We currently do not have a consistent release cadence of SensorExplorer to the Microsoft Store. It is as needed for the time being. Please email me if there is a need!

**Pull request merged**
