### PR TITLE
move additional KM tracing to nonpaged section

### PR DESCRIPTION
**Pull request by erik-pe**
This change moves some additional KM WPP providers from paged to nonpaged.

### CODE REVIEW

**Comment by erik-pe** [comment]
I'd appreciate if folks could give the remaining nonpaged providers a look to see if there are any others that need to be pulled into paged.

**Comment by rahul-ramadas** [comment]
BTHUSB should also be moved.

**Comment by erik-pe** [comment]
`Microsoft.Windows.Bluetooth.BTHUSB` is the BTHUSB manifested ETW. I was under the impression that only KM WPP needed to be nonpaged.

**Comment by rahul-ramadas** [comment]
It might be worth finding out from someone who knows more, but I don't think that is the case. It controls the `EVENT_TRACE_USE_PAGED_MEMORY` flag on the ETW session and the [documentation](https://docs.microsoft.com/en-us/windows/desktop/etw/logging-mode-constants) says you can't use that flag for kernel-mode ETW providers (WPP uses legacy ETW). When an event is fired, the payload needs to be deposited into the buffer synchronously, so if a driver fires an event at >= `DISPATCH_LEVEL`, the buffer cannot be paged out.

**Comment by erik-pe** [comment]
You're probably right, given that bthport's etw events are nonpaged as well.

**Pull request merged**
