### PR TITLE
add additional Verbose level providers to BluetoothStack.wprp

### PR DESCRIPTION
**Pull request by erik-pe**
This change to `BluetoothStack.wprp` adds several more WPP providers to the newly-defined Verbose level and changes the file encoding to UTF-8 since it seems to be supported better than the previous little-endian UTF-16.

### CODE REVIEW

**Comment by erik-pe** [comment]
>         </EventCollectorId>

Since the diff will be a little rough until both the old and new versions are UTF-8 (without a BOM), this is the primary collector change.

---
Refers to: bluetooth/tracing/BluetoothStack.wprp:747 in e0b9ea2. [](commit_id = e0b9ea22390d350f4acb9efffe4fa00767c7d1d7, deletion_comment = False)

**Comment by erik-pe** [comment]
>             <EventProviderId Value="Microsoft.Windows.Bluetooth.WPP.bthusb.Verbose"/>

Also added this.

---
Refers to: bluetooth/tracing/BluetoothStack.wprp:751 in e0b9ea2. [](commit_id = e0b9ea22390d350f4acb9efffe4fa00767c7d1d7, deletion_comment = False)

**Comment by nimazure** [comment]
>     <EventProvider Id="Microsoft.Windows.Bluetooth.WPP.BTAG" Name="B0F691EA-EF99-45A0-8AF4-2C2BCF7F67B8" Level="4" NonPagedMemory="false">

And this

---
Refers to: bluetooth/tracing/BluetoothStack.wprp:162 in e0b9ea2. [](commit_id = e0b9ea22390d350f4acb9efffe4fa00767c7d1d7, deletion_comment = False)

**Comment by nimazure** [comment]
>       <Keywords>

And this

---
Refers to: bluetooth/tracing/BluetoothStack.wprp:273 in e0b9ea2. [](commit_id = e0b9ea22390d350f4acb9efffe4fa00767c7d1d7, deletion_comment = False)

**Pull request merged**
